### ISSUE TITLE
Loading and registering a type 1 AASX file

### ISSUE THREAD

**Issue by imcardle** [eclipse-basyx/basyx-dotnet-components#1]
Please can you give an example of how I can load and register a static (type 1) AASX file?  I have read the documentation for the Java components and found that it is possible using the AASXPackageManager class - but I could not find an equivalent class in the .net components.

**Comment by HansG89** [comment]
Same Question from my side.
I just saw, that the [AAS Server Docker Image](https://github.com/eclipse-basyx/basyx-java-components/blob/c8104f61072d0d098301eaccf0a93f668dc93f3a/basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/AASServerComponent.java#L142) uses the same mechanism. Is there somethin similar in .Net?

**Comment by HansG89** [comment]
Found it in the [Application Repo](https://github.com/eclipse-basyx/basyx-dotnet-applications)

@imcardle here you can see how to [load an AASX file in .Net](https://github.com/eclipse-basyx/basyx-dotnet-applications/blob/main/BaSyx.AASX.Server.Http.App/Program.cs#L163)

**Comment by imcardle** [comment]
Thank you @HansG89 !
